Support for slide links in publication pages
academicpages/academicpages.github.io pull request #2126
Opened 2024-05-15 22:49 UTC by saravan2

1. Introduced slidesurl to encode link for slides
2. Added optional field : slides_url to markdown_generator/publication. tsv  and modified publication.ipynb to parse the optional field and append slidesurl 
3. ipython notebook execution regenerated _publications/*-paper-title-number-{1-3}.md 
4. Updated _includes/archive-single.html and _layouts/single.html to display links to slides when slidesurl is set
5. Added sample slides in files/*

2024-05-16 15:27 UTC, rjzupkoii commented on _publications/2009-10-01-paper-title-number-1.md
> -The contents above will be part of a list of publications, if the user clicks the link for the publication than the contents of section will be rendered as a full page, allowing you to provide more i
This part should not be removed since it is a hint to new users of how the template behaves.

2024-05-16 15:27 UTC, rjzupkoii commented on _publications/2009-10-01-paper-title-number-1.md
> +This paper is about the number 1. The number 2 is left for future work.
This part should not be present since it is generated by the template automatically.

2024-05-16 15:30 UTC, rjzupkoii commented on _publications/2010-10-01-paper-title-number-2.md
Ditto above comments on paper one.

2024-05-16 15:30 UTC, rjzupkoii commented on _publications/2015-10-01-paper-title-number-3.md
Ditto above comments on paper one.

2024-05-16 15:36 UTC, rjzupkoii requested changes
Thanks for submitting the pull request with these changes! Having support for slides would be a useful addition to the template, but some changes need to be made in order to bring it into line with how the template works and it's overall design. I've made some comments on the relevant files with the changes that need to be made.

2024-05-16 15:36 UTC, rjzupkoii commented on _includes/archive-single.html
> +    {% endif %}
This should be after or adjacent to the link to download the paper, not before the citation.

2024-05-16 15:36 UTC, rjzupkoii commented on _layouts/single.html
> +        {% endif %}
This should be after or adjacent to the link to download the paper, not before the citation.

2024-05-16 15:36 UTC, rjzupkoii commented on _publications/2009-10-01-paper-title-number-1.md
> +This paper is about the number 1. The number 2 is left for future work.
This part should not be present since it is generated by the template automatically.

2024-05-16 15:36 UTC, rjzupkoii commented on _publications/2009-10-01-paper-title-number-1.md
> -The contents above will be part of a list of publications, if the user clicks the link for the publication than the contents of section will be rendered as a full page, allowing you to provide more i
This part should not be removed since it is a hint to new users of how the template behaves.

2024-05-16 15:36 UTC, rjzupkoii commented on _publications/2009-10-01-paper-title-number-1.md
> +Recommended citation: Your Name, You. (2009). "Paper Title Number 1." <i>Journal 1</i>. 1(1).
This should all be generated by the template as part of `_layouts/single.html` or `_includes/archive-single.html`

2024-05-16 15:36 UTC, rjzupkoii commented on _publications/2010-10-01-paper-title-number-2.md
Ditto above comments on paper one.

2024-05-16 15:36 UTC, rjzupkoii commented on _publications/2015-10-01-paper-title-number-3.md
Ditto above comments on paper one.

2024-05-16 17:46 UTC, saravan2 commented
Thanks for the review. I added commit ebbb512e1f690bd406dc46c4a05be783a9a65b55 with relevant changes.

2024-05-17 00:33 UTC, rjzupkoii approved these changes

2024-05-17 00:33 UTC, merged

2024-05-17 01:37 UTC, saravan2 commented
@rjzupkoii There is a typo `elseif` when it should have been `elsif` in Line 65 of `_includes/archive-single.html` in my commit ebbb512e1f690bd406dc46c4a05be783a9a65b55

I noticed it when I went through the logs of https://github.com/academicpages/academicpages.github.io/actions/runs/9121047739

I regret my oversight.

2024-05-17 02:19 UTC, rjzupkoii commented
@saravan2 No worries! I was able to fix it and also tweak things a bit as well.